### ISSUE TITLE
Would anyone like to take over ownership of this library?

### ISSUE THREAD

**Issue by jackmott** [verpeteren/rust-simd-noise#43]
I feel bad that I haven't had time to respond to any issues, if anyone has been playing with this that would like to become the maintainer, let me know.

**Comment by arduano** [comment]
Only if it's to keep it in sync. I currently have no use case for this library so it would be hard to develop it past basic maintenance.

**Comment by jackmott** [comment]
ok, I don't want to burden you, I'll see if I can keep it in sync or I have someone else in mind who might be interested.

**Comment by arduano** [comment]
I could try to send a PR later when I further update simdeez, although I'll try avoiding major breaking changes in simdeez anyway (outside deprecations)

**Comment by verpeteren** [comment]
I will take over this library. I will close this issue.
@arduano : This library and simdeez are closely related, so we should indeed sync up.
@jackmott : thanks for the trust and all the work that you did!

**Comment by arduano** [comment]
@verpeteren btw have you seen the changes I've been making on my current simdeez branch? There will potentially be a bit of work to sync this up without relying on deprecated functions (almost all of which I'll keep ofc).

In case you haven't seen, the idea is that:
- The Simd trait no longer has any of the old functions on it (well, it still has all the old functions but they just proxy the new functions, and are marked as deprecated).
- There are a lot more shared traits that describe the different behaviors of different vector types under different instruction sets.
- The runtime generate macro now only generates 1 function, and that function automatically picks the best instruction set. Not exposing functions for other instruction sets allowed me to remove the "unsafe" attribute from almost all functions.
- If you really need underlying instruction set access, you can get it with a feature flag in the crate, but exposing it also makes a bunch of operations unsafe again.

oh and also I've made a much more robust testing framework and caught a lot of undefined behavior and bugs in the old code
