### ISSUE TITLE
Refactor the codebase to the updated simdeez API

### ISSUE THREAD

**Issue by arduano** [verpeteren/rust-simd-noise#47]
Leaving this issue here to track the fact that I'm working on it, let me know if that would conflict with anything

**Comment by arduano** [comment]
An example of how the new API looks like would be here:
https://github.com/verpeteren/rust-simd-noise/compare/master...arduano:rust-simd-noise:master
currently in the cell_32 file. 

@verpeteren This may create some pretty nasty merge conflicts, should I wait for any of your other tasks to be finished before continuing?

**Comment by arduano** [comment]
Oh and also, I've added Arm Neon support to simdeez in that new version and I'm planning to add wasm as well, so the library would be able to support those too.

**Comment by verpeteren** [comment]
@arduano: I'll close this (tracking) issue, I just [merged the simdeez v2 into master](https://github.com/verpeteren/rust-simd-noise/pull/54)
